sas_front_homepage:
    path:     /{_locale}
    defaults: { _controller: SASFrontBundle:Front:index }
sas_front_homepage2:
    path:     /
    defaults: { _controller: SASFrontBundle:Front:index }
sas_front_about:
    path:     /{_locale}/about
    defaults: { _controller: SASFrontBundle:Front:about }
sas_front_contact:
    path:     /{_locale}/contact
    defaults: { _controller: SASFrontBundle:Front:contact }
sas_front_gallery:
    path:     /{_locale}/gallery
    defaults: { _controller: SASFrontBundle:Front:gallery }
